version: "2.0"
services:
  api:
    container_name: jsshop-api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: yarn start:dev
    volumes:
      - ./api/:/usr/app
      - /usr/app/node_modules
    ports:
      - 3010:3010
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    links:
      - mariadb
  ui:
    container_name: jsshop-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # command: yarn start
    volumes:
      - './ui:/usr/app'
      - '/usr/app/node_modules'
  mariadb:
    container_name: jsshop-db
    image: mariadb
    command: mysqld --sql_mode=""
    volumes:
      - jsshop:/var/lib/mysql/data
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=jsshop
      - MYSQL_PASSWORD=jsshop
      - MYSQL_DATABASE=jsshop
  adminer:
    container_name: jsshop-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mailhog:
    container_name: jssho-mailhog
    image: mailhog/mailhog
    user: root
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
    jsshop:
