version: "2.0"
services:
  backend:
    container_name: jsshop-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - 3010:3010
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  frontend:
    container_name: jsshop-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - './frontend:/usr/app'
      - '/usr/app/node_modules'
  mariadb:
    container_name: jsshop-db
    image: mariadb
    command: mysqld --sql_mode=""
    volumes:
      - jsshop:/var/lib/mysql/data
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=jsshop
      - MYSQL_PASSWORD=jsshop
      - MYSQL_DATABASE=jsshop
  adminer:
    container_name: jsshop-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    jsshop:
